#! /bin/sh

. /etc/default/pve-migration-monitor
action=$1
file=$2

if [[ $(basename $file) = sed* ]]
then
    # If file name starts with "sed", it is a temporary file created by sed command
    # from the vm-public-ip script, ignore the file
    exit
fi

logger -t $LOGGER_TAG "Dispatch: detected action $1 on file $2"

if [ "$action" = "MOVED_FROM" ]; then
    script_dir=$SCRIPT_DIR/down.d
elif grep -q 'lock: migrate' "$file"; then
    # The host was moved here. Note that that event also gets called when moving away
    # but config file will have lock: migrate
    # that's why we check lock: migrate in qemu-server config
    logger -t $LOGGER_TAG "Dispatch: vm is locked (moving away), exiting !"
    exit
else
    script_dir=$SCRIPT_DIR/up.d
    # When live migrating from a hypervisor, the config file for the vm is moved 
    # several times, then disappears.
    # We wait one second to check that this is not happening here.
    wait 1
    if [ ! -f $file ] ; then
        logger -t $LOGGER_TAG "Dispatch: file $file disappeared, exiting !"
        exit
    fi
fi

for script in $script_dir/*; do
    logger -t $LOGGER_TAG "Dispatch: launching $script $file"
    [ -x $script ] && $script $file
done
