#! /bin/sh

. /etc/default/pve-migration-monitor

[ -n "$RESOURCE_DIR" ] && $SCRIPT_DIR/init_routes

inotifywait -q -m -e moved_to,moved_from --format "%e %w/%f" --exclude '\.conf\.tmp\.[0-9]+$' /etc/pve/qemu-server /etc/pve/lxc $RESOURCE_DIR | while read file; do $SCRIPT_DIR/dispatch $file; done
